# Generated by Django 5.2.4 on 2025-07-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material', models.CharField(max_length=10)),
                ('Finish', models.CharField(max_length=5)),
                ('Length', models.IntegerField()),
                ('Price_per_length', models.IntegerField()),
                ('Order_info', models.CharField(max_length=200)),
                ('Order_Number', models.IntegerField()),
            ],
        ),
    ]
